-- Update ElevenLabs Data
UPDATE public.ai_models
SET
    -- 0) Basic Info Update
    description = '텍스트를 입력하면 사람과 구별할 수 없는 감정 섞인 목소리로 읽어주는, 현존 최고의 AI 음성 합성 및 복제 플랫폼.',
    website_url = 'https://elevenlabs.io',
    
    -- 1) Meta Info (Badges)
    meta_info = '{
        "korean_support": true,
        "login_required": "required",
        "platforms": ["Web", "API", "Mobile App (Reader)"],
        "target_audience": "유튜버(내레이션), 오디오북 제작자, 게임 개발자, 시각장애인"
    }'::jsonb,
    
    -- 2) Pricing Info
    pricing_model = 'Freemium (무료 + 유료 구독)',
    free_tier_note = '**월 10,000자(약 10분)** 생성 무료. 단, **상업적 이용 불가**하며 반드시 ElevenLabs 출처를 표기해야 함.',
    pricing_plans = '[
        {
            "plan": "Free",
            "price": "무료",
            "target": "개인/취미",
            "features": "10,000자/월, 상업적 이용 불가, 기본 음성"
        },
        {
            "plan": "Starter",
            "price": "$5/월",
            "target": "유튜버(입문)",
            "features": "30,000자/월, 상업적 이용 허용, 즉시 목소리 복제"
        },
        {
            "plan": "Creator",
            "price": "$11/월",
            "target": "전문 제작자",
            "features": "100,000자/월 (약 2시간), 고품질(192kbps), PVC(정교한 복제)"
        },
        {
            "plan": "Pro",
            "price": "$99/월",
            "target": "기업/팀",
            "features": "500,000자/월, 44.1kHz 초고음질, API 사용량 증대"
        }
    ]'::jsonb,

    -- 3) Pros and Cons
    pros = ARRAY[
        '압도적 리얼함: 숨소리, 머뭇거림, 감정(화남, 기쁨 등)을 조절할 수 있어 기계음 특유의 어색함이 거의 없습니다.',
        'Voice Cloning: 내 목소리나 특정인(동의 필요)의 목소리를 1분 샘플만으로 복제해 텍스트를 읽게 할 수 있습니다.',
        'Dubbing Studio: 영상 파일만 올리면 AI가 언어를 번역하고, 원본 화자의 목소리 톤을 유지한 채 더빙까지 입혀줍니다.',
        'Sound Effects: "숲속의 새소리", "문 닫는 소리" 등 효과음도 텍스트로 생성할 수 있습니다.'
    ],
    cons = ARRAY[
        '글자 수 차감: 한글은 영어보다 글자 수 차감이 빠르게 느껴질 수 있으며, 마음에 안 들어서 다시 생성해도 크레딧이 깎입니다.',
        '비용: Creator 플랜($11/월)도 긴 유튜브 영상 몇 개 만들면 금방 소진되어, 헤비 유저에겐 비쌀 수 있습니다.'
    ],

    -- 4) Recommendations
    recommendations = '{
        "recommended": [
            {
                "target": "얼굴 없는 유튜버",
                "badge": "YouTuber",
                "reason": "내 목소리 노출은 싫지만 기계음(TTS)은 쓰기 싫은 분"
            },
            {
                "target": "글로벌 진출",
                "badge": "Global",
                "reason": "한국어 영상을 영어/일본어 등으로 더빙해서 수출하고 싶은 분 (Dubbing)"
            },
            {
                "target": "게임/앱 개발",
                "badge": "Dev",
                "reason": "캐릭터에게 각각 다른 성격의 목소리를 부여하고 싶은 분"
            }
        ],
        "not_recommended": [
            {
                "target": "실시간 방송",
                "reason": "텍스트를 음성으로 변환하는 데 렌더링 시간이 필요하므로(Turbo 모델은 빠르지만) 실시간 대화용으로는 API 연동이 필요합니다"
            },
            {
                "target": "완전 무료 상업",
                "reason": "무료 플랜으로 만든 음원을 유튜브 수익 창출 영상에 쓰면 약관 위반입니다"
            }
        ]
    }'::jsonb,

    -- 5) Key Features
    key_features = '[
        {
            "name": "Text to Speech",
            "description": "감정 조절이 가능한 초고품질 음성 합성"
        },
        {
            "name": "Instant Voice Cloning",
            "description": "1분 샘플로 즉석 목소리 복제"
        },
        {
            "name": "Dubbing Studio",
            "description": "영상 번역 및 다국어 자동 더빙"
        },
        {
            "name": "Sound Effects",
            "description": "텍스트 프롬프트로 효과음 생성"
        },
        {
            "name": "Speech to Speech",
            "description": "내가 말한 녹음 파일의 목소리 톤만 다른 사람으로 변환"
        },
        {
            "name": "Projects",
            "description": "장문(오디오북) 제작을 위한 전용 에디터"
        }
    ]'::jsonb,

    -- 6) Usage Tips
    usage_tips = ARRAY[
        '크레딧 이월: 사용하지 않은 크레딧은 일부 이월되기도 하지만(Roll-over), 기본적으로 소멸되니 월말에 몰아서 쓰는 게 좋습니다.',
        '저작권 표기: 무료 플랜 사용자는 반드시 "Audio generated by ElevenLabs" 문구를 영상 설명란 등에 남겨야 합니다.'
    ],

    -- 7) Privacy Info
    privacy_info = '{
        "security": "Voice Cloning 기능은 본인 목소리 인증 절차(캡차 등)를 거쳐야 하며, 타인의 목소리를 무단 도용하면 계정이 정지됩니다."
    }'::jsonb,

    -- 8) Alternatives
    alternatives = '[
        {
            "name": "OpenAI Voice (TTS)",
            "description": "좀 더 저렴한 API 비용으로 무난한 퀄리티를 원한다면"
        },
        {
            "name": "Typecast",
            "description": "한국어 연기 톤과 캐릭터가 훨씬 다양한 국산 툴 (가성비 좋음)"
        }
    ]'::jsonb,

    -- 9) Media Info
    media_info = '[
        {
            "title": "ElevenLabs: The Future of Voice",
            "url": "https://www.youtube.com/watch?v=0",
            "platform": "YouTube"
        }
    ]'::jsonb

WHERE name ILIKE '%ElevenLabs%' OR name ILIKE '%일레븐랩스%';
