// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddwbivpdhwpwnjsrtsim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkd2JpdnBkaHdwd25qc3J0c2ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNzE5NzUsImV4cCI6MjA3MTg0Nzk3NX0.KYVm3y6_HmINbmNGznvf5eDXQ_QQAz9IIUIRlGWzA4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});